### PR TITLE
fix: improve responsiveness to changing app status

### LINKED ISSUE #5347: Freigh promotion stalls in Unknown health state for 3 minutes
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [~] I've pasted the output of `kargo version`.
* [-] I've pasted logs, if applicable.

# Description

A freight is being auto promoted to a stage after a build. The health status indicates "Unknown" status for what seems 3 minutes until it goes healthy. There is Analysis Template configured for the stage. The Stage indicates the Verify is running, but it is not. It will start after health status changes to "Healthy".

However, going into a Stages menu and selecting "Refresh" (after 5-10 seconds) will get the health status changed to "Healthy" and the verification starts.

This happen on all (3) stages on all our projects/repos.

# Screenshots

Image

# Steps to Reproduce
1. (auto) promote a freight
2. see it happen
3. wait 5-10 seconds
4. stages menu and selecting "Refresh"

# Version

```
1.8.2
```

# Logs

```
```

### LINKED ISSUE #5636: Reduce log level for "Stage health evaluated to Unknown" during active promotions
## Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

## Description

During active promotions, the Stage controller logs ERROR level messages for "Stage health evaluated to Unknown" even though this is expected transient behavior during normal operations.

PR #4871 (v1.7.3) refined **when** Unknown health is treated as an error, but the log level remains ERROR for the "promotion in progress" case. When `!lastPromo.Status.Phase.IsTerminal()` evaluates true (i.e., promotion is Running), the controller returns an error at line 479 of `pkg/controller/stages/regular_stages.go`, which controller-runtime logs at ERROR level.

**Impact:**
- Log noise during normal promotion operations
- Difficult to distinguish actual errors from expected transitional states
- Alert fatigue if monitoring ERROR level logs

**Related:**
- Discussion #5024
- PR #4871 (fix that refined when to error, but not the log level)
- Issue #5045 (closed, but log level concern not fully addressed)

## Screenshots

N/A

## Steps to Reproduce

1. Create a Stage with health checks configured
2. Trigger a promotion to that Stage
3. Observe kargo-controller logs during the promotion's Running phase
4. ERROR logs appear repeatedly until the promotion completes and health becomes Healthy

## Version

```
version: v1.8.7
```

## Logs

```
2026-01-27T09:22:16Z ERROR controller/controller.go:421 Reconciler error {"controller": "stage", "controllerGroup": "kargo.akuity.io", "controllerKind": "Stage", "Stage": {"name":"candidate-errata","namespace":"v4-17"}, "namespace": "v4-17", "name": "candidate-errata", "reconcileID": "7364c7fa-7f02-4828-80e0-076f7ce57df4", "error": "Stage health evaluated to Unknown"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:421
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1
sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:296
```

## Suggested Fix

Consider one of the following approaches for the "promotion in progress" case specifically:

1. Use `ctrl.Result{RequeueAfter: backoffDuration}` with calculated backoff instead of returning an error
2. Add a check for `!lastPromo.Status.Phase.IsTerminal()` and handle it separately without returning an error
3. Log at INFO/DEBUG level before returning the error for transitional states

Example change in `regular_stages.go`:

```go
if lastPromo := status.LastPromotion; lastPromo != nil &&
    lastPromo.Status != nil &&
    !lastPromo.Status.Phase.IsTerminal() {
    // Promotion in progress - this is expected, requeue without error
    return status, nil  // or use ctrl.Result{RequeueAfter: ...}
}
```

## Code Reference

The relevant code is in `pkg/controller/stages/regular_stages.go` around line 472-479:

```go
if lastPromo := status.LastPromotion; lastPromo == nil ||
    lastPromo.Status == nil ||
    !lastPromo.Status.Phase.IsTerminal() ||
    lastPromo.Status.Phase == kargoapi.PromotionPhaseSucceeded {
    // Scenario 2: There was no last Promotion or there was and it was
    // successful. Whatever the reason the Stage health evaluated to
    // Unknown, an unsuccessful Promotion wasn't it.
    return status, errors.New("Stage health evaluated to Unknown") // nolint: staticcheck
}
```

The condition `!lastPromo.Status.Phase.IsTerminal()` captures the "promotion in progress" case, which is a normal operational state that arguably should not produce ERROR level logs.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #5347

Fixes #5636

Possible alternative to #5984

cc @alexmt 

## Problem

Argo CD executes operations and assesses health in separate reconciliation
loops. This can lead to stale health status and, in turn, an overly optimistic
assessment of Stage health.

We've known about this for a long time and have gone through _many_ iterations
of attempting to solve this elegantly. A purely event-driven approach has been
elusive because there are many cases where the App's reconciliation loop writes
no changes to the App, so a watcher on Apps that enqueues related Stages for
reconciliation couldn't quite be relied upon. We ended up going through several
different iterations of a 10-second cooldown period. Last op completed less than
10 seconds ago? Throw an error. The Stage reconciler goes into progressive
backoff. It shouldn't be long before another attempt finds trustworthy health
status.

This brought a new problem along with it -- if something else is causing
frequent operations on an App (maybe auto-sync is enabled), it's possible, with
some bad luck, to get stuck in a spiral of untrusted App health status for a
_very_ long time.

## Fix

No more cooldown period. We simply look at the App's `reconciledAt` field. If
its date/time is >= the time the last operation completed, then we know health
must have been assessed at some point post-op and we can immediately trust the
App's health status.

If these conditions are NOT met, we force a hard refresh of the App so that they
_will_ be met on the next reconciliation attempt. A new and improved App watcher
enqueues Stages for reconciliation promptly after the forced refresh completes.

### CODE REVIEW

File: pkg/controller/stages/event_handlers.go [hunk 1]
```diff
@@ -460,16 +460,103 @@ func appHealthOrSyncStatusChanged[T any](ctx context.Context, e event.TypedUpdat
...
+	}
+	finishedAt, _, _ := unstructured.NestedString(
+		newUn, "status", "operationState", "finishedAt",
+	)
+	if finishedAt == "" {
+		return false
+	}
+	// RFC3339 timestamps are lexicographically orderable, so string
+	// comparison preserves chronological order.
+	return oldReconciledAt == "" || oldReconciledAt < finishedAt
```
Comment (fuskovic) [inline pkg/controller/stages/event_handlers.go:559]: TIL
