### PR TITLE
fix(controller): make token cache ttl more dynamic

### LINKED ISSUE #5610: github app authentication: transient git clone issues over https
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

About 15% of the time, git clone operations using github app authentication over https fail with a "404 repo not found". After talking to github support, they had the following to say

> We apologise for the inconvenience caused. Private repository access failures are surfaced as 404's to avoid revealing whether a private repository exists. Our logs for Git clone requests headed to that repository on 2026-01-16 show ~85% of calls were successful; however, the rest were rejected due to an authentication error. To confirm, this isn't anything to do with rate limiting, rather it's a problem with the credentials that are being passed when performing the git clone operation. The most likely causes for this are attempting to authenticate with a bad/expired token, or the token not being presented at all.
 
> At the moment, our logs aren’t granular enough to tell which of those two conditions is occurring. Since GitHub App installation access tokens expire quickly (1hr lifetime), would you be able to add lightweight logging for each git attempt that confirms a token was provided (no token value - just presence/length) and records the token “issued at” and “expires at” timestamps? Given that the majority of clone attempts succeed while a subset intermittently fail, this points to possible reuse of an expired GitHub App installation token, likely due to caching or refresh timing issues. 

They ruled out rate limiting and suggest this is possibly from use of an expired cached auth token.

https://github.com/akuity/kargo/blob/main/pkg/credentials/github/app.go#L61
https://github.com/patrickmn/go-cache/blob/master/cache.go

I looked at the caching implementation and a 40 minute expiration time should be covering the 1 hour token expiry. I wonder if there might be an issue with the cleanup interval being 1 hour and trying to overwrite the token between the expiration interval and cleanup interval? Some sort of write-after-read consistency issue going on?

Maybe some debug logging could help track down this error should it keep happening. I didn't notice any debug logging in that section of the code I could use if I turned on debug logging either.

# Screenshots

# Steps to Reproduce

Don't yet have a minimal reproduction instructions other than the following conditions that are currently true in my setup

* Use github app authentication
* Have ~40 projects, each with a warehouse subscription to a different private repo

I've seen 404 errors on many different repos so it didn't appear isolated to a specific repo.

# Version

```
{
  "Version": "v1.8.4",
  "BuildDate": "2025-11-25T22:29:20Z",
  "GitCommit": "dc38d05ff871ace7ae40fc23ef333ca717c96909",
  "GitTreeDirty": false,
  "GoVersion": "go1.25.4",
  "Compiler": "gc",
  "Platform": "linux/arm64"
}
```

# Logs

```
2026-01-16T22:32:54Z    ERROR    controller/controller.go:421    Reconciler error    {"controller": "warehouse", "controllerGroup": "kargo.akuity.io", "controllerKind": "Warehouse", "Warehouse": {"name":"my-repo","namespace":"my-repo"}, "namespace": "my-repo", "name": "my-repo", "reconcileID": "c8c238ae-1060-4a0a-a65d-fecc093
17272", "error": "error discovering artifacts: error discovering commits: error discovering commits from git repo \"https://github.com/my-org/my-repo\": error cloning git repo \"https://github.com/my-org/my-repo\": error cloning repo \"https://github.com/my-org/my-repo\" into \"/tmp/repo-1964468500/repo\":
 error executing cmd [/usr/bin/git clone --no-tags --single-branch https://kargo@github.com/my-org/my-repo /tmp/repo-1964468500/repo]: Cloning into '/tmp/repo-1964468500/repo'...\nremote: Repository not found.\nfatal: repository 'https://github.com/my-org/my-repo/' not found\n"}

```

### PR DESCRIPTION
**Pull request by krancour**
Fixes #5610

Supersedes #5615 

In many cases, though not all, we have access to a token's expiry date/time.

For such cases, it is safer to derive cache TTL durations from the expiry than to make assumptions about how long the token is valid for.

This also adds debug level logging with details of token expiry (if known) and corresponding cache entry TTL.

### CODE REVIEW

File: pkg/credentials/ecr/access_key.go [hunk 1]
```diff
@@ -93,9 +108,22 @@ func (p *AccessKeyProvider) GetCredentials(
...
 	}
-
-	// Cache the encoded token
-	p.tokenCache.Set(cacheKey, encodedToken, cache.DefaultExpiration)
+	logger.Debug("obtained new auth token")
+
+	// Cache the encoded token, preferring a TTL derived from the actual token
+	// expiry when available.
+	ttl := cache.DefaultExpiration
+	if !expiry.IsZero() {
```
Comment (hiddeco) [inline pkg/credentials/ecr/access_key.go]: We are doing this in multiple places, probably better to extract it to a helper:

```go
func CalculateCacheTTL(expiry time.Time, margin time.Duration) time.Duration {}
```

Comment (krancour) [reply pkg/credentials/ecr/access_key.go]: Fixed in https://github.com/akuity/kargo/pull/5684/commits/c0be8f675db69d94dd52aa4cb3e1188da367edaf

**Review by thomastaylor312 — APPROVED** [review]
