### PR TITLE
fix app syncing to account for syncpolicy/options

### LINKED ISSUE #874: Kargo doesn't instruct Argo CD to create namespace when option is set on the Application
I have a `Stage` that has auto promotion enabled in it's `PromotionPolicy`. So when I first deploy the Stage it tries to sync the Argo CD Application

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: dev-app
  project: default
  source:
    path: app
    repoURL: https://github.com/christianh814/kargo-demo-deploy
    targetRevision: env/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

However it FAILS

image

The error from Argo CD is "namespace not found"

image

When I use this app with "Vanilla" Argo CD, it works as expected.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #874

Create namespace option (among others) wasn't being honored when Kargo programmatically syncs an App.

### CODE REVIEW

**Review by jessesuen — APPROVED** [review]

File: internal/controller/promotion/argocd.go [hunk 1]
```diff
@@ -159,10 +159,28 @@ func (a *argoCDMechanism) doSingleUpdate(
...
 		},
 	}
+	if app.Spec.SyncPolicy != nil {
+		if app.Spec.SyncPolicy.Retry != nil {
+			app.Operation.Retry = *app.Spec.SyncPolicy.Retry
+		}
+		if app.Spec.SyncPolicy.SyncOptions != nil {
+			app.Operation.Sync.SyncOptions = app.Spec.SyncPolicy.SyncOptions
+		}
+	}
```
Comment (jessesuen) [inline internal/controller/promotion/argocd.go:183]: This looks consistent with autoSync() implementation of argo-cd controller, which is what we want.

Comment (krancour) [reply internal/controller/promotion/argocd.go:183]: Thanks @jessesuen!
