### PR TITLE
fix: improve freight availability checks

### LINKED ISSUE #2365: bug: need to verify freight being promoted is wanted
Toward the beginning of the promotion process, we do validate that the Freight being promoted is _available_ to the Stage it is being promoted to:

https://github.com/akuity/kargo/blob/fd47846bcddb26e340abc0a1ccb52c44e43d8243/internal/controller/promotions/promotions.go#L471-L478

There is, however, an edge case wherein a piece of Freight could be _available_ to the Stage, but not _wanted._

It would/could happen if a piece of Freight from a particular origin had been manually approved for the Stage in question and since that time the Stage was edited to no longer request Freight from that origin.

Such a promotion should not proceed.

Note: @hiddeco has a recollection of being unable to reproduce this. I will attempt to do so when time permits, but if he's right, we'll just close this.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #2365 

After approaching this problem a few different ways, the thing that came out cleanest was treating the question of whether a piece of Freight is _wanted_ by a given Stage as just another dimension of whether that Freight is _available_ to that Stage.

1b3d577e491eddf6e91b7e463a41ae8c02399419 is some pre-requisite refactoring that made the more prescient refactoring and enhancements in 75d6fcc7d66da56006be5fc371e8c15f965d0de9 a bit easier.

6753bad5a0cb046e891e320508acce410a00356b just updates existing usage of the refactored availability check accordingly.

2559c0c2323e5c544966df8361267e1580e1bc4b adds the availability check to the Promo creation webhook so that availability checks aren't bypassed when using `kubectl` instead of `kargo` or the UI.

### CODE REVIEW

File: internal/api/promote_downstream_v1alpha1.go [hunk 1]
```diff
@@ -92,22 +92,26 @@ func (s *server) PromoteDownstream(
 		}
 		return nil, connect.NewError(connect.CodeNotFound, err)
 	}
-	if !s.isFreightAvailableFn(
-		freight,
-		"",                  // approved for not considered
-		[]string{stageName}, // verified in
-	) {
```
Comment (krancour) [inline internal/api/promote_downstream_v1alpha1.go:99]: Awkward usage of `IsFreightAvailable()`, which was written awkwardly to accommodate this.

File: internal/api/promote_downstream_v1alpha1.go [hunk 2]
```diff
@@ -92,22 +92,26 @@ func (s *server) PromoteDownstream(
...
 		return nil, connect.NewError(
 			connect.CodeInvalidArgument,
 			fmt.Errorf(
-				"Freight %q is not available to Stage %q",
+				"Freight %q is not available to Stages down stream from %q",
 				freightName,
 				stageName,
 			),
 		)
 	}
```
Comment (krancour) [inline internal/api/promote_downstream_v1alpha1.go:112]: More direct way of answering "can this Freight move downstream from here?"

File: internal/api/promote_downstream_v1alpha1.go [hunk 3]
```diff
@@ -160,16 +164,23 @@ func (s *server) PromoteDownstream(
...
 	var allStages kargoapi.StageList
 	if err := s.client.List(ctx, &allStages, client.InNamespace(stage.Namespace)); err != nil {
 		return nil, connect.NewError(connect.CodeInternal, err)
 	}
 	var downstreams []kargoapi.Stage
 	for _, s := range allStages.Items {
 		for _, req := range s.Spec.RequestedFreight {
+			if !req.Origin.Equals(&origin) {
+				continue
+			}
```
Comment (krancour) [inline internal/api/promote_downstream_v1alpha1.go:183]: Pretty sure it was an undiscovered bug that this check wasn't here already. I believe the potential has existed for Freight to be promoted to all of a Stage's downstreams _including_ those that may be uninterested in the Freight in question.

File: api/v1alpha1/freight_helpers.go [hunk 4]
```diff
@@ -86,34 +86,24 @@ func GetFreightByAlias(
...
-			return true
-		}
+	if _, approved := freight.Status.ApprovedFor[stage.Name]; approved {
+		return true
 	}
-	if stage != "" {
-		if _, ok := freight.Status.ApprovedFor[stage]; ok {
-			return true
+	for _, req := range stage.Spec.RequestedFreight {
+		if freight.Origin.Equals(&req.Origin) {
```
Comment (krancour) [inline api/v1alpha1/freight_helpers.go:98]: This line is the cornerstone of the PR.

File: internal/webhook/promotion/webhook.go [hunk 5]
```diff
@@ -221,15 +221,38 @@ func (w *webhook) ValidateCreate(
...
+			promo.Name,
+			field.ErrorList{
+				field.Invalid(
+					field.NewPath("spec", "freight"),
+					promo.Spec.Freight,
+					"Freight is not available to this Stage",
+				),
+			},
+		)
+	}
```
Comment (krancour) [inline internal/webhook/promotion/webhook.go:252]: Now we don't miss out on this check when using `kubectl` instead of `kargo` or the UI.
