### PR TITLE
fix(api server): show what permissions clusterroles contribute to a kargo role

### LINKED ISSUE #4046: Kargo does not support a RoleBinding with a reference to a ClusterRole
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Kargo does not support a RoleBinding with a reference to a ClusterRole. With such a RoleBinding defined it is impossile to use Kargo RBAC. 

With such a role is defined in the project namespace you get the following error:
Role.rbac.authorization.k8s.io "<cluster-role>" not found

The issue appears to be that Kargo looks only for Role objects when a RoleBinding is used and not for a ClusterRole even if it is referenced in the RB.

The role binding in question in our cluster has nothing to do with Kargo, but is a default rolebinding getting created with the namespace. Because of this other rolebinding, RBAC definitons are not being applied in Kargo nor is it possible to view them via UI or CLI.

# Screenshots

Image

# Steps to Reproduce

Create a Rolebinding with a reference to a ClusterRole in a project namespace. 
Try to open the Roles tab in the kargo UI. 

# Version

```
1.4.4
```

# Logs

```
Role.rbac.authorization.k8s.io "<cluster-role>" not found
```

# Suggestions

- Kargo should check the roleRef.kind field and search for the appropriate object (role or clusterRole) 
- Optionaly kargo should only load serviceAccounts/role/rolebindigs that are marked with a custom annotation or label (to avoid loading irrelevant objects)

### PR DESCRIPTION
**Pull request by krancour**
Supersedes #5897

Fixes #4046

See https://github.com/akuity/kargo/pull/5897#issuecomment-4057335473 for details.

### CODE REVIEW

**Comment by emmanuel099** [comment]
Our platform team tested this on OpenShift, works as expected.

The OpenShift cluster roles `deployer` and `builder` are now visible in Kargo. No more errors when accessing projects.

image

Definitely much better than https://github.com/akuity/kargo/pull/5897, thanks again!

**Comment by krancour** [comment]
Thanks for verifying @emmanuel099!

File: pkg/server/rbac/roles.go [hunk 1]
```diff
@@ -345,14 +348,14 @@ func (c *rolesDatabase) GetAsResources(
 
 	sa := &corev1.ServiceAccount{}
 	if err := c.client.Get(ctx, objKey, sa); err != nil {
-		return nil, nil, nil, fmt.Errorf(
+		return nil, nil, nil, nil, fmt.Errorf(
```
Comment (fuskovic) [inline pkg/server/rbac/roles.go]: NIT: I've looked at this code before and thought the function signature had too many return values. 
I think consolidating the return values into a single struct type could clean this up a bit e.g.

```go
type RbacResources struct {
     serviceAccount
     roles
     clusterRoles
     roleBindings
}
```

Comment (krancour) [reply pkg/server/rbac/roles.go]: I also wasn't crazy about it and almost had done exactly what you're suggesting. I should. Or I will, rather.

Comment (krancour) [reply pkg/server/rbac/roles.go]: Refactored in 14814fbb866a5163f58ed323fed5cf8d2719aea7
