### PR TITLE
fix allowTags in image subscriptions

### LINKED ISSUE #820: RegEx not working for `allowTags`
Using `allowTags` for images doesn't seem to provide a freight

```yaml
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/christianh814/kargo-demo-app
        updateStrategy: Latest
        allowTags: '^[0-9a-f]{6}$'
```

This gives the following error...

```
error syncing image repo subscriptions: error getting latest suitable
      tag for image "quay.io/christianh814/kargo-demo-app": found no suitable version
      of image "quay.io/christianh814/kargo-demo-app"
```

Moving it to `ignoreTags` returns the right tags

```yaml
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/christianh814/kargo-demo-app
        updateStrategy: Latest
        #allowTags: '^[0-9a-f]{6}$'
        ignoreTags:
          - latest
```

This might be an Image Updater issue

### PR DESCRIPTION
**Pull request by krancour**
Fixes #820

cc @christianh814

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]

File: internal/images/images.go [hunk 1]
```diff
@@ -41,7 +42,9 @@ func GetLatestTag(
 		Strategy:   img.ParseUpdateStrategy(string(updateStrategy)),
 	}
 	if allowTags != "" {
-		vc.MatchFunc, vc.MatchArgs = img.ParseMatchfunc(allowTags)
+		vc.MatchFunc, vc.MatchArgs = img.ParseMatchfunc(
+			fmt.Sprintf("regexp:%s", allowTags),
```
Comment (krancour) [inline internal/images/images.go:46]: I didn't read the docs well enough...

https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#filtering-tags
