### PR TITLE
fix: refresh freightline after warehouse completes refresh

### LINKED ISSUE #1202: Warehouse refresh from UI should update freightline
# Proposed Feature

When clicking refresh on a Warehouse, the freightline should be updated automatically once the refresh annotation is cleared.

NOTE: we used to do this when refreshing the stage, but now that Warehouses are responsible for producing freight (and not stages), we need the UI to adjust accordingly.

# Motivation

Currently I have to do a browser refresh to see new freight.

# Suggested Implementation

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #1202 (for real this time 🙂)

### CODE REVIEW

File: ui/src/features/project/project-details/nodes/repo-node.tsx [hunk 1]
```diff
@@ -37,7 +37,10 @@ export const RepoNode = ({ nodeData, children }: Props) => {
         <div className='text-ellipsis whitespace-nowrap overflow-hidden'>
           {nodeData.warehouseName}
         </div>
-        {nodeData.type !== NodeType.REPO_CHART && <FontAwesomeIcon icon={faBuilding} />}
+        <div className='flex items-center'>
+          {nodeData.refreshing && <FontAwesomeIcon icon={faCircleNotch} spin className='mr-2' />}
```
Comment (rbreeze) [inline ui/src/features/project/project-details/nodes/repo-node.tsx:41]: Adds refresh indicator for Warehouse nodes

File: ui/src/features/project/project-details/project-details.tsx [hunk 2]
```diff
@@ -133,17 +131,69 @@ export const ProjectDetails = () => {
...
+            ] as Warehouse[];
+          }
+        }
+
+        if (refresh[e.warehouse?.metadata?.name || '']) {
+          delete refresh[e.warehouse?.metadata?.name || ''];
+          refetchAvailableFreight();
+        }
+
+        const refreshing = e.warehouse?.metadata?.annotations['kargo.akuity.io/refresh'];
```
Comment (rbreeze) [inline ui/src/features/project/project-details/project-details.tsx:163]: If refresh annotation is found on a warehouse, we don't refetch freight yet. Instead, save it to a map which indicates it _started_ refreshing

**Review by jessesuen — APPROVED** [review]
rubber stamp approval
