### PR TITLE
fix(controller): make stage spec.vars referenceable from verifications

### LINKED ISSUE #4124: Stage spec.vars not referenceable  from verifications
# Description

In v1.5 we added Stage spec level vars, so that verifications could reference them. However, when I try to reference it and pass it to an AnalysisTemplate, I get error:

`error building AnalysisRun for Stage "vars" and Freight collection "3cf57b82db812e4abedfdedf3393676225a6b2d0" in namespace "kargo-demo-18": build spec: build arguments: evaluate argument "pokemon": cannot fetch pokemon_1 from <nil> (1:7) | vars.pokemon_1 | ......^`

# Screenshots

Image

# Steps to Reproduce

Run example here:
https://github.com/akuity/kargo-examples/pull/3/files

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: vars
  namespace: kargo-demo-18
spec:
  vars:
  - name: pokemon_1
    value: pikachu
  requestedFreight:
  - origin:
      kind: Warehouse
      name: vars
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: pokemon_2
        value: charmander
      steps:
      - task:
          name: promo-process
        vars:
        - name: pokemon_3
          value: bulbasaur
  verification:
    analysisTemplates:
    - name: pokemon-query
    args:
    - name: pokemon
      value: ${{ vars.pokemon_1 }}
```

# Version

```
v1.5.0
```

### PR DESCRIPTION
**Pull request by krancour**
Fixes #4124

### CODE REVIEW

File: internal/controller/stages/regular_stages.go [hunk 1]
```diff
@@ -1342,6 +1342,7 @@ func (r *RegularStageReconciler) startVerification(
 				exprfn.DataOperations(ctx, r.client, stage.Namespace)...,
 			),
 		},
+		rollouts.WithVars(stage.Spec.Vars),
```
Comment (hiddeco) [inline internal/controller/stages/regular_stages.go:1345]: There is no need to create a `WithVars`, you can just set `Vars` in `rollouts.WithArgumentEvaluationConfig`.

Comment (hiddeco) [reply internal/controller/stages/regular_stages.go:1345]: When doing this, I think the type of `Vars` should change to `kargoapi.ExpressionVariable`, and the `ArgumentVariable` can be dropped then. That's what was supposed to happen in my original PR.

Comment (krancour) [reply internal/controller/stages/regular_stages.go:1345]: 🤦‍♂️

Comment (krancour) [reply internal/controller/stages/regular_stages.go:1345]: There _is_ a conversion from `[]kargoapi.ExpressionVariable` to `[]rollouts.ArgumentVariable` that needs to happen item-by-item. Does that influence your thinking at all?

Comment (hiddeco) [reply internal/controller/stages/regular_stages.go:1345]: See my second comment :-).

Comment (krancour) [reply internal/controller/stages/regular_stages.go:1345]: I think they crossed in the mail.

Comment (krancour) [reply internal/controller/stages/regular_stages.go]: Should be all set now.

**Review by hiddeco — APPROVED** [review]
