### PR TITLE
fix: auto-detect ghe.com domains in github provider

### LINKED ISSUE #5568: `git-open-pr` does not automatically detect GitHub Enterprise for `ghe.com`
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When using the `git-open-pr` promotion step the creation of the PR will fail with the following error:

`error creating git provider service: no registered providers for https://{name}.ghe.com/repo/dummy.git`

I think the detection of the correct provider is not selecting Github when the domain is ghe.com.

# Steps to Reproduce

Configure a Github Enterprise repository on the ghe.com domain.
Create a promotion with the git-open-pr step

# Version

1.8.5

# Logs

```
2026-01-12T16:10:00Z	ERROR	promotions/promotions.go:362	error executing Promotion	{"namespace": "kargo-architecture", "promotion": "management-roadmap.01kesfh82073c15kdwxkscn9jw.b1390df", "namespace": "kargo-architecture", "promotion": "management-roadmap.01kesfh82073c15kdwxkscn9jw.b1390df", "stage": "management-roadmap", "freight": "b1390df933dc8a82260a1da7c5d85cfc213dd646", "error": "step \"task-1::open-pr\" met error threshold of 1: error running step \"task-1::open-pr\": error creating git provider service: no registered providers for https://{name}.ghe.com/test/dummy.git"}
github.com/akuity/kargo/pkg/controller/promotions.(*reconciler).Reconcile.func3
	github.com/akuity/kargo/pkg/controller/promotions/promotions.go:362
github.com/akuity/kargo/pkg/controller/promotions.(*reconciler).Reconcile
	github.com/akuity/kargo/pkg/controller/promotions/promotions.go:364
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
	sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:216
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:461
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:421
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1
	sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:296
```

### PR DESCRIPTION
**Pull request by singhvibhanshu**
Fixes #5568

## Description
The current GitHub provider logic only checks if the hostname contains "github", which causes failures for GitHub Enterprise Cloud users on `ghe.com` domains.

This PR updates the predicate in `pkg/gitprovider/github/github.go` to explicitly support `ghe.com`.

## Changes
- Updated `pkg/gitprovider/github/github.go` to recognize `ghe.com` as a valid GitHub provider.
- Added a new test case in `pkg/gitprovider/github/github_test.go` to verify `ghe.com` detection.

## Verification
- [x] Ran `go test ./pkg/gitprovider/github` (All tests passed).
- [x] Ran `make hack-lint-go` (No linting errors).

### CODE REVIEW

File: pkg/gitprovider/github/github_test.go [hunk 1]
```diff
@@ -16,6 +16,46 @@ import (
...
+	}
+
+	for _, tc := range testCases {
+		t.Run(tc.name, func(t *testing.T) {
+			// Accessing the unexported 'registration' variable directly
+			// because we are in package 'github'
+			result := registration.Predicate(tc.url)
+			if result != tc.expected {
+				t.Errorf("Predicate(%q) = %v; want %v", tc.url, result, tc.expected)
+			}
```
Comment (hiddeco) [inline pkg/gitprovider/github/github_test.go]: Can you please use the `require` library?

Comment (singhvibhanshu) [reply pkg/gitprovider/github/github_test.go]: Updated to use `require.Equal`. Thanks.

File: pkg/gitprovider/github/github.go [hunk 2]
```diff
@@ -31,10 +31,10 @@ var registration = gitprovider.Registration{
...
 		}
 		// We assume that any hostname with the word "github" in it can use this
-		// provider. NOTE: We will miss cases where the host is GitHub Enterprise
-		// but doesn't incorporate the word "github" in the hostname. e.g.
-		// 'git.mycompany.com'
-		return strings.Contains(u.Host, ProviderName)
+		// provider. We also explicitly support 'ghe.com' (GitHub Enterprise Cloud).
+		// NOTE: We will miss cases where the host is GitHub Enterprise
+		// but doesn't incorporate the word "github" or "ghe.com" (e.g. 'git.mycompany.com').
+		return strings.Contains(u.Host, ProviderName) || strings.Contains(u.Host, "ghe.com")
```
Comment (hiddeco) [inline pkg/gitprovider/github/github.go]:
```suggestion
		return strings.Contains(u.Host, ProviderName) || strings.HasSuffix(u.Host, ".ghe.com")
```

Comment (singhvibhanshu) [reply pkg/gitprovider/github/github.go]: You're right, `HasSuffix` is much safer here to avoid partial matches. I've applied the suggestion and fixed the DCO sign-off.
Thanks!
