### PR TITLE
fix: images table did not load intermittently

### LINKED ISSUE #1775: Every refresh several times you will see "No images available"
https://github.com/akuity/kargo/assets/2680725/edca62e7-1a75-4cc2-bae9-0e7739af4092

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #1775

### CODE REVIEW

File: ui/src/features/project/pipelines/images.tsx [hunk 1]
```diff
@@ -122,12 +122,20 @@ export const Images = ({ projectName, stages }: { projectName: string; stages: S
...
   const [showHistory, setShowHistory] = useLocalStorage(`${projectName}-show-history`, false);
 
+  useEffect(() => {
+    setImageURL(images.keys().next().value as string);
+  }, [images]);
+
+  useEffect(() => {
+    setCurImage(images.get(imageURL));
+  }, [imageURL]);
+
```
Comment (rpelczar) [inline ui/src/features/project/pipelines/images.tsx:135]: I think you can use `useMemo` here.

**Review by rpelczar — CHANGES_REQUESTED** [review]

File: ui/src/features/project/pipelines/images.tsx (hunk 1 above)
Comment (rbreeze) [reply ui/src/features/project/pipelines/images.tsx]: We can for `curImage` but not `imageURL` because we need to `setImageURL` elsewhere as well
