### PR TITLE
fix: add indicator to Argo CD deep links

### LINKED ISSUE #1724: UI: It's not obvious what "Argo CD" is. Add icon or indicator that it is a deep link
Screenshot 2024-04-01 at 08 39 46

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #1724

CleanShot 2024-04-02 at 10 42 27@2x
CleanShot 2024-04-02 at 10 42 49@2x

### CODE REVIEW

File: ui/src/features/stage/stage-actions.tsx [hunk 1]
```diff
@@ -80,20 +86,24 @@ export const StageActions = ({ stage }: { stage: Stage }) => {
...
     <Space size={16}>
       {argoCDAppsLinks.length === 1 && (
-        <Button
-          type='link'
-          onClick={() => window.open(argoCDAppsLinks[0]?.url, '_blank', 'noreferrer')}
-          size='small'
-        >
-          Argo CD
-        </Button>
+        <Tooltip title={argoCDAppsLinks[0]?.label}>
```
Comment (jessesuen) [inline ui/src/features/stage/stage-actions.tsx:89]: Is the system-wide label we name the instance? If so, should we instead title the link to the name of the application we are linking to?

Comment (rbreeze) [reply ui/src/features/stage/stage-actions.tsx:89]: Oh, this is already done, just a few lines above: https://github.com/akuity/kargo/blob/0e8f38e55a98c132643285d84ecb02528c67e427/ui/src/features/stage/stage-actions.tsx#L75

**Review by jessesuen — APPROVED** [review]
